name: remote_services_example
description: A sample command-line application
dependencies:
  remote_services: any
  logging: any
  browser: any
dev_dependencies:
  exitlive_protobuf_builder:
    git: git@github.com:exitlive/exitlive-protobuf-builder.git
