name: iris_example
description: An iris example
dependencies:
  iris: ">= 0.2.4"
  logging: any
  browser: any
dev_dependencies:
  exitlive_protobuf_builder:
    git: git@github.com:exitlive/exitlive-protobuf-builder.git
