name: iris_example
description: An iris example
dependencies:
  iris:
    path: /Users/enyo/git/iris
  logging: any
  browser: any
dev_dependencies:
  exitlive_protobuf_builder:
    git: git@github.com:exitlive/exitlive-protobuf-builder.git
